openapi: 3.1.0
info:
  title: NEN Business Administrion API
  description: |
    API to interact with the ERP capability in the Business Administration Domain
    Audience: clients continually updating a shadow library of standards content.
  contact:
    name: NEN Servicedesk IT
    email: ServicedeskITRegie@nen.nl
    url: 'https://www.nen.nl/contact-nl'
  version: 1.1.1
tags:
- name: Healthcheck
  description: to verify if the service is up and running healthily
- name: Event
  description: to publish updates on the state of a resource
- name: Subscription
  description: to manage subscriptions for event channels
- name: Committee
  description: Committee resource
- name: Member
  description: Member resource
# Define the anchors once (before referencing them)
x-default-responses:
  getItem: &standardGetWithEtagResponses
    '304':
      $ref: './NenOasFragments.json#/responses/304'
    '400':
      $ref: './NenOasFragments.json#/responses/400'
    '401':
      $ref: './NenOasFragments.json#/responses/401'
    '403':
      $ref: './NenOasFragments.json#/responses/403'
    '404':
      $ref: './NenOasFragments.json#/responses/404'
    '408':
      $ref: './NenOasFragments.json#/responses/408'
    '500':
      $ref: './NenOasFragments.json#/responses/500'
    '503':
      $ref: './NenOasFragments.json#/responses/503'
    '504':
      $ref: './NenOasFragments.json#/responses/504'
  getCollection: &standardGetResponses
    '400':
      $ref: './NenOasFragments.json#/responses/400'
    '401':
      $ref: './NenOasFragments.json#/responses/401'
    '403':
      $ref: './NenOasFragments.json#/responses/403'
    '404':
      $ref: './NenOasFragments.json#/responses/404'
    '408':
      $ref: './NenOasFragments.json#/responses/408'
    '429':
      $ref: './NenOasFragments.json#/responses/429'
    '500':
      $ref: './NenOasFragments.json#/responses/500'
    '503':
      $ref: './NenOasFragments.json#/responses/503'
    '504':
      $ref: './NenOasFragments.json#/responses/504'
paths:
  /health:
    get:
      description: |
        Check the status of the service. Returns UP or DOWN with the time of the check.
        $comment: to be discussed what health is being checked; the gateway health, or of all the services 'behind' the gateway
      tags:
      - Healthcheck
      summary: Healthstatus service
      operationId: getHealthStatus
      parameters:
      - $ref: './NenOasFragments.json#/parameters/correlationId'
      responses:
        '200':
          description: Service status received
          headers:
            X-Correlation-Id:
              $ref: './NenOasFragments.json#/headers/correlationId'
          content:
            application/json:
              schema:
                $ref: './NenOasFragments.json#/schemas/healthStatus'
        <<: *standardGetResponses
      security:
      - clientCredentials:
        - monitor
  /events/{channel}:
    post:
      summary: restful endpoint for publishing a CloudEvent via HTTP
      # Note: for future use only. Current SAP does not publish events. Consumers are polling for updates instead.
      description: Publishes a CloudEvent to the broker channel.
      operationId: postEvent
      tags:
      - Event
      parameters:
      - $ref: './NenOasFragments.json#/parameters/correlationId'
      - name: channel
        in: path
        required: true
        schema:
          $ref: '../CDM/cloudEvents.json#/committeeChannel'
      - name: subscriptionId
        in: query
        required: true
        schema:
          $ref: '../CDM/cloudEvents.json#/definitions/handle'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/refId'
      responses:
        '202':
          $ref: './NenOasFragments.json#/responses/202'
        '400':
          $ref: './NenOasFragments.json#/responses/400'
        '401':
          $ref: './NenOasFragments.json#/responses/401'
        '403':
          $ref: './NenOasFragments.json#/responses/403'
        '500':
          $ref: './NenOasFragments.json#/responses/500'
        '503':
          $ref: './NenOasFragments.json#/responses/503'
        '504':
          $ref: './NenOasFragments.json#/responses/504'
      security:
      - clientCredentials:
        - committee:publish
    get:
      description: List of events for a channel
      operationId: listEvents
      tags:
      - Event
      parameters:
      - $ref: './NenOasFragments.json#/parameters/correlationId'
      - name: channel
        in: path
        required: true
        schema:
          $ref: '../CDM/cloudEvents.json#/definitions/committeeChannel'
      responses:
        '200':
          description: List of events for the channel
          headers:
            X-Correlation-Id:
              $ref: './NenOasFragments.json#/headers/correlationId'
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  additionalProperties: false
                  properties:
                    eventId:
                      $ref: '../CDM/cloudEvents.json#/properties/id'
                    refId:
                      $ref: '#/components/schemas/refId'
          links:
            getEvent:
              $ref: './NenOasFragments.json#/links/events'
      security:
      - clientCredentials:
        - committee:publish
        - committee:subscribe
  /events/{channel}/{eventId}:
    get:
      summary: Retrieve CloudEvents over HTTP
      # Note: for future use only. Current SAP does not publish events. Consumers are polling for updates instead.
      description: Get a specific CloudEvents from a channel.
      operationId: getEvent
      tags:
      - Event
      parameters:
      - $ref: './NenOasFragments.json#/parameters/correlationId'
      - $ref: '#/components/parameters/channel'
      - $ref: '#/components/parameters/subscriptionId'
      - name: eventId
        in: path
        required: true
        schema:
          $ref: '../CDM/cloudEvents.json#/definitions/iddef'
      responses:
        '200':
          description: Event retrieved successfully
          headers:
            X-Correlation-Id:
              $ref: './NenOasFragments.json#/headers/correlationId'
          content:
            application/json:
              schema:
                $ref: '../CDM/cloudEvents.json#'
        '400':
          $ref: './NenOasFragments.json#/responses/400'
        '401':
          $ref: './NenOasFragments.json#/responses/401'
        '403':
          $ref: './NenOasFragments.json#/responses/403'
        '404':
          description: Event not found for the given channel and eventId
          headers:
            X-Correlation-Id:
              $ref: './NenOasFragments.json#/headers/correlationId'
        '500':
          $ref: './NenOasFragments.json#/responses/500'
        '503':
          $ref: './NenOasFragments.json#/responses/503'
        '504':
          $ref: './NenOasFragments.json#/responses/504'
      security:
      - clientCredentials:
        - committee:publish
        - committee:subscribe
  /subscriptions:
    post:
      operationId: createSubscription
      description: Create a subscription
      parameters:
        - $ref: './NenOasFragments.json#/parameters/correlationId'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '../CDM/cloudEvents.json#/definitions/subscriptionRequest'
      tags:
      - Subscription
      responses:
        "201":
          description: Created successfully
          content:
            application/json:
              schema:
                $ref: '../CDM/cloudEvents.json#/definitions/subscription'
          headers:
            X-Correlation-Id:
              $ref: './NenOasFragments.json#/headers/correlationId'
        "400":
          $ref: './NenOasFragments.json#/responses/400'
        "401":
          $ref: './NenOasFragments.json#/responses/401'
        "403":
          $ref: './NenOasFragments.json#/responses/403'
      security:
      - clientCredentials:
        - committee:publish
        - committee:subscribe
  /subscriptions/{channel}:
    description: Manage CloudEvents subscriptions for Committee events. Subscriptions are used to receive updates on changes to committee and member data via the eventing system, as an alternative to polling for updates via the REST API.
    summary: Create, retrieve, and manage CloudEvents subscriptions 
    parameters:
    - $ref: './NenOasFragments.json#/parameters/correlationId'
    - $ref: '#/components/parameters/channel'
    get:
      operationId: getSubscriptions
      description: Retrieve list of subscriptions for the given channel
      tags: 
      - Subscription
      responses:
        "200":
          description: OK
          headers:
            X-Correlation-Id:
              $ref: './NenOasFragments.json#/parameters/correlationId'
          content:
            application/json:
              schema:
                $ref: '../CDM/cloudEvents.json#/definitions/subscriptionList'
          links:
            getEvents:
              $ref: './NenOasFragments.json#/links/eventList'
            postEvents :
              $ref: './NenOasFragments.json#/links/postEvents'
        <<: *standardGetResponses
      security:
      - clientCredentials:
        - committee:admin
    delete:
      operationId: endSubscription
      description: Unsubscribe from the given channel
      tags: 
      - Subscription
      parameters:
        - $ref: '#/components/parameters/subscriptionId'
      responses:
        "204":
          description: No Content
          headers:
            X-Correlation-Id:
              $ref: './NenOasFragments.json#/parameters/correlationId'
        "400":
          $ref: './NenOasFragments.json#/responses/400'
        "404":
          $ref: './NenOasFragments.json#/responses/404'
  /committees:
    get:
      description: List of committees, filtered by query parameters, sorted by updatedAt (oldest first)
      operationId: listCommittees
      summary: List of committees
      tags:
      - Committee
      parameters:
      - $ref: './NenOasFragments.json#/parameters/fromDate'
      - $ref: './NenOasFragments.json#/parameters/maxNumberOfItems'
      - $ref: './NenOasFragments.json#/parameters/correlationId'
      responses:
        '200':
          description: Committee list
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/committeeList'
          links:
            getCommittee:
              operationId: getCommitteeById
              parameters:
                nenCommitteeId: "$response.body#/references/nenCommittees/nenCommitteeId"
          headers:
            X-Correlation-Id:
              $ref: './NenOasFragments.json#/headers/correlationId'
        '206':
          description: Partial Committee list
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/committeeList'
          links:
            getCommittee:
              operationId: getCommitteeById
              parameters:
                nenCommitteeId: "$response.body#/references/nenCommittees/nenCommitteeId"
          headers:
            X-Correlation-Id:
              $ref: './NenOasFragments.json#/headers/correlationId'
            X-Next:
              $ref: './NenOasFragments.json#/headers/next'
        <<: *standardGetResponses
      security:
      - clientCredentials:
        - committee:read      
  /committees/{committeeId}:
    get:
      description: Retrieve NEN committee with details if its eTag value has changed or if no eTag value is given
      operationId: getCommitteeById
      tags:
      - Committee
      summary: Retrieve committee by Id
      parameters:
      - name: committeeId
        in: path
        required: true
        schema:
          $ref: '../CDM/NenIdentifiers.json#/definitions/nenCommitteeId'
        description: Unique ID of the NEN committee
      - $ref: './NenOasFragments.json#/parameters/correlationId'
      - $ref: './NenOasFragments.json#/parameters/ifChanged'
      responses:
        '200':
          description: Committee details
          content:
            application/json:
              schema:
                $ref: '../CDM/NenCommittee_V1.1.0.json#'
          links:
            getMembers:
              operationId: getMember
              parameters:
                familyAdminId: "$response.body#/references/committeeMembers/memberId"
          headers:
            X-Correlation-Id:
              $ref: './NenOasFragments.json#/headers/correlationId'
            ETag:
              $ref: './NenOasFragments.json#/headers/eTag'
        <<: *standardGetWithEtagResponses
      security:
      - clientCredentials:
        - committee:read      
  /members:
    get:
      description: List of committee members, filtered by query parameters, sorted by updatedAt (oldest first)
      operationId: listMembers
      summary: List of committee members
      tags:
      - Member
      parameters:
      - name: committeeId
        in: query
        description: Filter memberList for a specific committee
        required: false
        schema:
          $ref: '../CDM/NenIdentifiers.json#/definitions/nenCommitteeId'
      - name: nenOnly
        in: query
        description: filter condition to get only NEN employees when yes
        required: false
      # default: false
        schema:
          type: boolean
      - $ref: './NenOasFragments.json#/parameters/fromDate'
      - $ref: './NenOasFragments.json#/parameters/maxNumberOfItems'
      - $ref: './NenOasFragments.json#/parameters/correlationId'
      responses:
        '200':
          description: Member list
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/memberList'
          links:
            getMember:
              operationId: getMemberById
              parameters:
                memberId: '$response.body#/references/memberId'
          headers:
            X-Correlation-Id:
              $ref: './NenOasFragments.json#/headers/correlationId'
        '206':
          description: Partial Member list
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/memberList'
          links:
            getCommittee:
              operationId: getMemberById
              parameters:
                nenCommitteeId: '$response.body#/references/memberId'
          headers:
            X-Correlation-Id:
              $ref: './NenOasFragments.json#/headers/correlationId'
            X-Next:
              $ref: './NenOasFragments.json#/headers/next'
        <<: *standardGetResponses
      security:
      - clientCredentials:
        - committee:read      
  /members/{memberId}:
    get:
      description: Retrieve committee member with details if its eTag value has changed or if no eTag value is given
      operationId: getMemberById
      tags:
      - Member
      summary: Retrieve member by Id
      parameters:
      - name: memberId
        in: path
        required: true
        schema:
          $ref: '../CDM/NenIdentifiers.json#/definitions/memberId'
        description: Unique ID of the NEN committee member
      - $ref: './NenOasFragments.json#/parameters/correlationId'
      - $ref: './NenOasFragments.json#/parameters/ifChanged'
      responses:
        '200':
          description: Member details
          content:
            application/json:
              schema:
                $ref: '../CDM/NenCommittee_V1.1.0.json#'
          headers:
            X-Correlation-Id:
              $ref: './NenOasFragments.json#/headers/correlationId'
            ETag:
              $ref: './NenOasFragments.json#/headers/eTag'
        <<: *standardGetWithEtagResponses
      security:
      - clientCredentials:
        - committee:read      
servers:
  - url: https://api.{stage}nen.nl/apis/committee/v1
    description: This API gets published in multiple environments for different stages of development. Note that naming is provisional, please update with final domain and hostname
    variables:
      stage:
        default: .
        description: a descriptor for the target environment, such as tst. acc. and demo.
  - url: https://localhost:5672/activemq
components:
  parameters:
    channel:
      in: path
      required: true
      schema:
        $ref: '../CDM/cloudEvents.json#/definitions/committeeChannel'
    subscriptionId:
      name: subscriptionId
      in: query
      required: true
      schema:
        $ref: '../CDM/cloudEvents.json#/definitions/handle'
  schemas:
    committeeList:
      type: array
      items:
        type: object
        additionalProperties: false
        properties:
          nenFamilyId:
            $ref: '../CDM/NenIdentifiers.json#/definitions/nenCommitteeId'
          updatedAt:
            $ref: '../CDM/NenFamily_V0.9.0.json#/properties/updatedAt'
    memberList:
      type: array
      items:
        type: object
        additionalProperties: false
        properties:
          nenMemberId:
            $ref: '../CDM/NenIdentifiers.json#/definitions/memberId'
          nenMember:
            description: whether the Member is a Nen employee  
            type: boolean
          updatedAt:
            $ref: '../CDM/NenFamily_V0.9.0.json#/properties/updatedAt'
    refId:
      oneOf:
      - $ref: '../CDM/NenIdentifiers.json#/definitions/nenCommitteeId'
      - $ref: '../CDM/NenIdentifiers.json#/definitions/memberId'
      - $ref: '../CDM/NenIdentifiers.json#/definitions/clientId'
  securitySchemes:
    # $comment: 'security is yet to be decided. To be updated later.'
    clientCredentials:
      # $ref: './NenOasFragments.json#/securitySchemes/app2AppOauth'
      # somehow the same as app2AppOauth in NenOasFragments, but scopes don't work (according to Spectral) when referencing it, so defined here again with the correct scopes for this API
      type: oauth2
      description: OAuth2 client credentials flow for server-to-server communication
      flows:
        clientCredentials:
          tokenUrl: https://auth.example.com/token
          refreshUrl: https://auth.example.com/token
          scopes:
            monitor: Monitor the service hhelth
            committee:read: Read access to committee info
            committee:publish: Publish committee messages to the broker
            committee:subscribe: Receive committee messages from the broker
            committee:admin: Administer committee cahnnels and subscriptions
